### ISSUE TITLE
Raise the pods-per-core limit

### ISSUE THREAD

**Issue by nmasse-itix** [nmasse-itix/OpenShift-Implementation-at-ITIX#2]
On a 8 cores server, the 80 pods limit is a bit low. 

The `pods-per-core` limit should be raised on install:

In the `/etc/origin/node/node-config.yaml`:
```yaml
kubeletArguments:
  node-labels:
  - region=infra
  pods-per-core:
  - "20"
```

Documentation: https://docs.openshift.com/container-platform/3.5/admin_guide/manage_nodes.html#admin-guide-max-pods-per-node
